### ISSUE TITLE
Ошибка при открытии *.dvs файла

### ISSUE THREAD

**Issue by gignorie** [KashaketCompany/DevelStudio-3.0-beta#139]
При открытии выдаёт ошибку о том что форма не найдена, связанная скорее всего с компонентами. Есть исключения, при открытии из большинства компонентов один из них видит нормально, остальные такие компоненты как таймер к примеру считает инородным(чужим).

**Comment by Kashaket** [comment]
Нет, штатный конвертер dvs.

**Comment by gignorie** [comment]
@Kashaket, Тогда не лучше демо проекты переработать, или выпилить?

P.s. Я могу заняться этим, если нет возможности.

**Comment by Kashaket** [comment]
@gignorie проблема не в демо-проектах, а в загрузке проектов вообще.
У Зайцева были костыли, а их как убирать - сразу что-то ломается.
Впринципе уже не важно, починил.
