### ISSUE TITLE
Chromium Proxy & UserAgent

### ISSUE THREAD

**Issue by zeko2010ss** [KashaketCompany/DevelStudio-3.0-beta#150]
Hello how can I set Proxy and change user-agent for chromium?

**Comment by Kashaket** [comment]
@zeko2010ss
Hello, at this point, the only option which you have is to use chromium_settings function:
[code]

chromium_settings(
        $cachePath,
        $userAgent,
        $version,
        $locale,
        $logFile,
        $extraPluginPath,
        $localeStorageQuote,
        $sessionStorageQuota,
        $jsFlags,
        $autoDetectProxy
);
[/code]

However, my general advice is not to use this project at all. It have too many bugs (had before me) and my fork is just unsuccessful attempt of reverse ingeneering. The original project is a shit, which based on stolen code, so, better use Delphi + P4D(PHP4Delphi) + Rtti (i will write extension especially).
Thanks
