### ISSUE TITLE
On run errors

### ISSUE THREAD

**Issue by limelect** [KashaketCompany/DevelStudio-3.0-beta#34]
On run errors

**Comment by Kashaket** [comment]
fck i fixed it up that error, and then it shows up again?...

**Comment by limelect** [comment]
Sorry still errors. in dll.
i cannot help because i gave up.

**Comment by Kashaket** [comment]
> Sorry still errors. in dll.
> i cannot help because i gave up.

Hmm this is not the same as i founded myself.

**Comment by Kashaket** [comment]
Баг связан с установкой Delphi более новой версии, студия почему-то пытается загрузить пакет отладчика оттуда. Причины не ясны, стоит выяснять, но вряд ли у кого-то будет похожая ситуация довольно часто повторяться.
